package common.lib.metadata;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-09-23")
public enum FormatType implements org.apache.thrift.TEnum {
  GENERIC(0),
  PARQUET(1),
  ORC(2),
  CSV(3);

  private final int value;

  private FormatType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static FormatType findByValue(int value) { 
    switch (value) {
      case 0:
        return GENERIC;
      case 1:
        return PARQUET;
      case 2:
        return ORC;
      case 3:
        return CSV;
      default:
        return null;
    }
  }
}
