include:
  - project: planetrover/templates
    file: templates.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'

default:
  tags: ["cluster"]
  image: ${CI_REGISTRY}/planetrover/infrastructure/maven:3.6.3-openjdk-8

stages:
  - build
  - upload

tdd-build:
  stage: build
  script:
    - mvn package assembly:single -DskipTests
  artifacts:
    paths:
      - target/sequoiadp-testing-1.0.0-fat-tests.jar

upload:
  stage: upload
  needs: ["tdd-build"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  extends:
    .package-push
  variables:
    GIT_STRATEGY: none
    PACKAGE_NAME: sequoiadp-testing
    PACKAGE_VERSION: 1.0.0
    FILE_NAME: target/sequoiadp-testing-1.0.0-fat-tests.jar
